<?php

return [
    'admin' => [
        'nhanvien.index',
        'nhanvien.show',
        'nhanvien.updateStatus',
        'nhanvien.create',
        'nhanvien.store',
        'nhanvien.edit',
        'nhanvien.update',
        'nhanvien.delete',
        'lichsu.index',
        'user.index',
        'admin.index',
        'admin.profile',
        'admin.profile.update',
        'admin.profile.resetPass',
        'lichsu.index',
        // ... các route name khác dành cho admin
    ],

    'news' => [
        'admin.index',
        'admin.profile',
        'admin.profile.update',
        'admin.profile.resetPass',
        'dstintuc.index',
        'dstintuc.update',
        'dstintuc.edit',
        'dstintuc.delete',
        'dstintuc.store',
        'dstintuc.formtin',
        'tintuc.xem',
        // ... các chức năng của nhân viên đăng tin
    ],

    'manage' => [

        'coso.index',
        'coso.store',
        'coso.edit',
        'coso.update',
        'coso.delete',
        'coso.export',

        'chuyenkhoa.index',
        'chuyenkhoa.store',
        'chuyenkhoa.edit',
        'chuyenkhoa.update',
        'chuyenkhoa.delete',
        'chuyenkhoa.export',

        'bacsi.index',
        'bacsi.create',
        'bacsi.store',
        'bacsi.edit',
        'bacsi.update',
        'bacsi.updateStatus',
        'bacsi.delete',
        'bacsi.lichkham',
        'getChuyenKhoa',
        'getAllChuyenKhoa',
        'getBacSi',
        'getAllBacSi',
        'bacsi.export',
        'lichkham.index',
        'lichkham.show',
        'lichkham.store',
        'lichkham.edit',
        'lichkham.update',
        'lichkham.delete',
        'lichkham.export',

        'taikhoanbenhnhan.index',
        'taikhoanbenhnhan.updateStatus',
        'taikhoanbenhnhan.xemhoso',
        'taikhoanbenhnhan.deleteXoaTK',
        'benhnhan.detail_lichhen',
        'benhnhan.edit',
        'benhnhan.update',
        'benhnhan.delete',

        'lichhen.index',
        'lichhen.delete',
        'lichhen.updateStatus',
        'lichhen.export',
        'benhnhan.show',
        'bacsi.show',

        'qltintuc.index',
        'qltintuc.updateStatus',
        'qltintuc.delete',
        'tintuc.xem',
        // ... các chức năng của quản lý
    ],

    'hospital' => [
        'coso.edit',
        'coso.update',

        'chuyenkhoa.index',
        'chuyenkhoa.store',
        'chuyenkhoa.edit',
        'chuyenkhoa.update',
        'chuyenkhoa.delete',
        'chuyenkhoa.export',

        'bacsi.index',
        'bacsi.create',
        'bacsi.store',
        'bacsi.edit',
        'bacsi.update',
        'bacsi.updateStatus',
        'bacsi.delete',
        'bacsi.lichkham',
        'getChuyenKhoa',
        'getBacSi',
        'getAllBacSi',
        'bacsi.export',

        'lichkham.index',
        'lichkham.show',
        'lichkham.store',
        'lichkham.edit',
        'lichkham.update',
        'lichkham.delete',
        'lichkham.export',

        'taikhoanbenhnhan.index',
        'taikhoanbenhnhan.updateStatus',
        'taikhoanbenhnhan.xemhoso',
        'taikhoanbenhnhan.deleteXoaTK',
        'benhnhan.detail_lichhen',
        'benhnhan.edit',
        'benhnhan.update',
        'benhnhan.delete',

        'lichhen.index',
        'lichhen.delete',
        'lichhen.export',
        'lichhen.updateStatus',
        'benhnhan.show',

        'thongkecoso.index',
        'thongkecoso.doanhthu',
        'thongkecoso.chartData',
        'thongkecoso.ajax',
        'bacsi.show',
        // ... các chức năng của quản lý
    ],

];
